from pathlib import Path

DEFAULT_CONFIG = {
    "log_sources": [
        {"name": "syslog", "path": "/var/log/syslog"},
        {"name": "auth", "path": "/var/log/auth.log"},
        {"name": "nginx_access", "path": "/var/log/nginx/access.log"},
        {"name": "nginx_error", "path": "/var/log/nginx/error.log"},
        {"name": "apache_access", "path": "/var/log/apache2/access.log"},
        {"name": "apache_error", "path": "/var/log/apache2/error.log"},
        {"name": "mail", "path": "/var/log/mail.log"},
        {"name": "audit", "path": "/var/log/audit/audit.log"},
    ],
    "detectors": [
        {
            "id": "ssh-auth-failure",
            "name": "SSH authentication failure",
            "description": "Detect repeated SSH authentication failures and brute-force attempts.",
            "pattern": r"(?i)(failed password|authentication failure|invalid user|reverse mapping checking|authentication error|invalid credentials|login failed)",
            "severity": "high",
            "block_on_match": True,
            "tags": ["ssh", "auth", "bruteforce"],
            "source": "MITRE ATT&CK",
            "reference": "T1110: Brute Force",
        },
        {
            "id": "smtp-auth-failure",
            "name": "SMTP authentication failure",
            "description": "Detect mail server authentication abuse and relay attacks.",
            "pattern": r"(?i)(authentication failure|relay denied|SMTP auth error|login failed|tls handshake error|invalid credentials)",
            "severity": "high",
            "block_on_match": True,
            "tags": ["mail", "smtp", "auth"],
            "source": "CISA",
            "reference": "Email Server Attack Patterns",
        },
        {
            "id": "owasp-sqli",
            "name": "OWASP SQL injection",
            "description": "Detect SQL injection payloads found in web requests.",
            "pattern": r"(?i)(union( all)? select|select .* from|insert into .* values|drop table|update .* set|information_schema|benchmark\(|sleep\(|or 1=1|--|#)",
            "severity": "high",
            "block_on_match": True,
            "tags": ["web", "attack", "sqli"],
            "source": "OWASP",
            "reference": "OWASP Top 10",
        },
        {
            "id": "owasp-xss",
            "name": "OWASP cross-site scripting",
            "description": "Detect XSS payloads and injection attempts in logs.",
            "pattern": r"(?i)(<script>|javascript:|onerror=|onload=|document\.cookie|window\.location|eval\(|document\.write|innerHTML)",
            "severity": "high",
            "block_on_match": True,
            "tags": ["web", "attack", "xss"],
            "source": "OWASP",
            "reference": "OWASP Top 10",
        },
        {
            "id": "owasp-lfi-rfi",
            "name": "OWASP file inclusion attempt",
            "description": "Detect local/remote file inclusion patterns in web access logs.",
            "pattern": r"(?i)(\.\./|/etc/passwd|php://input|expect://|data:text/plain|https?://.*\\.(php|asp|jsp))",
            "severity": "high",
            "block_on_match": True,
            "tags": ["web", "attack", "lfi", "rfi"],
            "source": "OWASP",
            "reference": "OWASP Top 10",
        },
        {
            "id": "owasp-command-injection",
            "name": "OWASP command injection",
            "description": "Detect command injection indicators inside web request payloads.",
            "pattern": r"(?i)(;\s*\b(cat|ls|whoami|netstat|ps|uname|id)\b|\$\(|\|\s*\/bin\/sh|`.+`|system\(|exec\(|popen\()",
            "severity": "high",
            "block_on_match": True,
            "tags": ["web", "attack", "command-injection"],
            "source": "OWASP",
            "reference": "OWASP Top 10",
        },
        {
            "id": "mitre-web-shell",
            "name": "MITRE web shell upload or access",
            "description": "Detect evidence of web shell activity and suspicious file upload behavior.",
            "pattern": r"(?i)(upload.*\.php|\.asp\?.*cmd=|shell\.php|webshell|cmd\.exe|powershell -enc|eval\(|base64_decode\()",
            "severity": "high",
            "block_on_match": True,
            "tags": ["web", "shell", "post-exploitation"],
            "source": "MITRE ATT&CK",
            "reference": "T1505: Server Software Component",
        },
        {
            "id": "elastic-malicious-user-agent",
            "name": "Elastic suspicious user agent",
            "description": "Detect suspicious or scanning user agents often used during web application attacks.",
            "pattern": r"(?i)(sqlmap|nikto|acunetix|nessus|dirbuster|masscan|curl/|wget/|python-requests|java/)",
            "severity": "medium",
            "block_on_match": True,
            "tags": ["recon", "scanner", "user-agent"],
            "source": "Elastic",
            "reference": "Elastic Security Detection Rules",
        },
        {
            "id": "cisa-exploit-scanner",
            "name": "CISA exploit scanner",
            "description": "Detect common exploit scanning and automated attack attempts.",
            "pattern": r"(?i)(CVE-\d{4}-\d{4,7}|exploit|shellshock|log4j|struts|upload.*\.php|\bphpmyadmin\b|/manager/html|/cgi-bin/)",
            "severity": "medium",
            "block_on_match": True,
            "tags": ["web", "exploit", "scanner"],
            "source": "CISA",
            "reference": "CISA Known Exploited Vulnerabilities",
        },
        {
            "id": "cisco-talos-scanning",
            "name": "Cisco Talos scanning and reconnaissance",
            "description": "Detect threat intelligence scanning patterns and reconnaissance signatures.",
            "pattern": r"(?i)(nmap|masscan|zmap|nessus|openvas|sqlmap|dirb|acunetix|nikto|hydra|medusa)",
            "severity": "medium",
            "block_on_match": True,
            "tags": ["recon", "scanner", "intel"],
            "source": "Cisco Talos",
            "reference": "Cisco Threat Intelligence",
        },
        {
            "id": "sans-dshield-scan",
            "name": "SANS DShield scanning indicator",
            "description": "Detect generic scanning and probing indicator tokens from community threat intel.",
            "pattern": r"(?i)(scan|probe|unauthorized access|fuzz|bruteforce|attack|suspicious request)",
            "severity": "medium",
            "block_on_match": True,
            "tags": ["recon", "scanner", "dshield"],
            "source": "SANS/DShield",
            "reference": "SANS Internet Storm Center",
        },
        {
            "id": "audit-denied",
            "name": "Audit denial event",
            "description": "Detect operating system audit and security denial messages.",
            "pattern": r"(?i)(audit.*denied|avc:|apparmor=\"denied\"|SELinux is preventing|denied .* illegal)",
            "severity": "medium",
            "block_on_match": False,
            "tags": ["audit", "security", "denied"],
            "source": "Linux Audit",
            "reference": "Auditd / AppArmor / SELinux Logs",
        },
    ],
    "response": {
        "enabled": True,
        "rate_limit_seconds": 600,
        "dry_run": False,
        "whitelist_ips": ["127.0.0.1", "::1"],
        "escalation_seconds": [3600, 86400, 0],
    },
    "logging": {
        "output_path": "/var/log/xphylax/events.jsonl",
        "console": True,
    },
    "notifications": {
        "telegram": {
            "enabled": True,
            "credentials_path": "/etc/xphylax.conf",
            "parse_mode": "MarkdownV2",
        },
    },
}

# Ensure the default log path exists in a safe local environment for development.
DEFAULT_CONFIG["logging"]["output_path"] = str(Path(DEFAULT_CONFIG["logging"]["output_path"]))
